# Automação Web e Busca de Informações com Python

#### Desafio: 

Trabalhamos em uma importadora e o preço dos nossos produtos é vinculado a cotação de:
- Dólar
- Euro
- Ouro

Precisamos pegar na internet, de forma automática, a cotação desses 3 itens e saber quanto devemos cobrar pelos nossos produtos, considerando uma margem de contribuição que temos na nossa base de dados.

Base de Dados: https://drive.google.com/drive/folders/1QHOQt1J7d5Z4sBFKL9GN699OcPh2aVaP?usp=sharing

Para isso, vamos criar uma automação web:

- Usaremos o selenium
- Importante: baixar o webdriver

In [28]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

### DOLAR
# ABRIR NAVEGADOR
navegador = webdriver.Chrome()

# CHAMAR URL DO SITE
navegador.get("https://google.com")

# IDENTIFICAR CAMPO DE BUSCA
navegador.find_element_by_xpath(
    '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys("cotação dólar")
navegador.find_element_by_xpath(
    '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER)

# PEGAR VALOR DO DOLAR
cotacao_dolar = navegador.find_element_by_xpath('//*[@id="knowledge-currency__updatable-data-column"]/div[1]/div[2]/span[1]').get_attribute("data-value")

# -----------------------------------------------------
### EURO
# CHAMAR URL DO SITE
navegador.get("https://google.com")

# IDENTIFICAR CAMPO DE BUSCA
navegador.find_element_by_xpath(
    '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys("cotação euro")
navegador.find_element_by_xpath(
    '/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER)

# PEGAR VALOR DO EURO
cotacao_euro = navegador.find_element_by_xpath('//*[@id="knowledge-currency__updatable-data-column"]/div[1]/div[2]/span[1]').get_attribute("data-value")

# -----------------------------------------------------
### OURO
# CHAMAR URL DO SITE
navegador.get("https://www.melhorcambio.com/ouro-hoje")

# PEGAR VALOR DO OURO
cotacao_ouro = navegador.find_element_by_xpath('//*[@id="comercial"]').get_attribute("value")
# REMOVERE VIRGULA DO OURO
cotacao_ouro = cotacao_ouro.replace(",",".")

# -----------------------------------------------------
# FECHAR NAVEGADOR
navegador.quit()
# -----------------------------------------------------
print(cotacao_dolar)
print(cotacao_euro)
print(cotacao_ouro)

C:\Users\lucas.fontana\AppData\Local\Temp\ipykernel_20260\3227680222.py:12: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  navegador.find_element_by_xpath(
C:\Users\lucas.fontana\AppData\Local\Temp\ipykernel_20260\3227680222.py:14: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  navegador.find_element_by_xpath(
C:\Users\lucas.fontana\AppData\Local\Temp\ipykernel_20260\3227680222.py:18: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  cotacao_dolar = navegador.find_element_by_xpath('//*[@id="knowledge-currency__updatable-data-column"]/div[1]/div[2]/span[1]').get_attribute("data-value")
C:\Users\lucas.fontana\AppData\Local\Temp\ipykernel_20260\3227680222.py:26: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  navegador.find_element_by_xpath(
C:\Users\lucas.fontana\AppData\Local\Temp\ipykernel_20260\3227680222.py:28: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  navegador.find_element_by_xpath(
C:\Users\lucas.fontana\AppData\Local\Temp\ipykernel_20260\3227680222.py:32: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  cotacao_euro = navegador.find_element_by_xpath('//*[@id="knowledge-currency__updatable-data-column"]/div[1]/div[2]/span[1]').get_attribute("data-value")
C:\Users\lucas.fontana\AppData\Local\Temp\ipykernel_20260\3227680222.py:40: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  cotacao_ouro = navegador.find_element_by_xpath('//*[@id="comercial"]').get_attribute("value")

5.235799999999999
5.522585709
307.21

### Agora vamos atualiza a nossa base de preços com as novas cotações

- Importando a base de dados

In [29]:
import pandas as pd

tabela = pd.read_excel("Produtos.xlsx")
display(tabela)

,Produtos,Preço Base Original,Moeda,Cotação,Preço Base Reais,Ajuste,Preço Final
0,Câmera Canon,999.99,Dólar,5,4999.95,1.40,6999.930
1,Carro Renault,4500.00,Euro,6,27000.00,2.00,54000.000
2,Notebook Dell,899.99,Dólar,5,4499.95,1.70,7649.915
3,IPhone,799.00,Dólar,5,3995.00,1.70,6791.500
4,Carro Fiat,3000.00,Euro,6,18000.00,1.90,34200.000
5,Celular Xiaomi,480.48,Dólar,5,2402.40,2.00,4804.800
6,Joia 20g,20.00,Ouro,350,7000.00,1.15,8050.000

- Atualizando os preços e o cálculo do Preço Final

In [30]:
# ATRIBUIR AS VARIÁVEIS NAS COTAÇÕES

Dolar = tabela["Moeda"] == "Dólar"
Euro = tabela["Moeda"] == "Euro"
Ouro = tabela["Moeda"] == "Ouro"

# ATUALIZAR TABELA COM OS NOVOS VALORES
tabela.loc[Dolar, "Cotação"] = float(cotacao_dolar)
tabela.loc[Euro, "Cotação"] = float(cotacao_euro)
tabela.loc[Ouro, "Cotação"] = float(cotacao_ouro)

# ATUALIZAR PREÇO BASE REAIS
tabela["Preço Base Reais"] = tabela["Preço Base Original"] * tabela["Cotação"]

# ATUALIZAR PREÇO FINAL
tabela["Preço Final"] = tabela["Preço Base Reais"] * tabela["Ajuste"]
display(tabela)

,Produtos,Preço Base Original,Moeda,Cotação,Preço Base Reais,Ajuste,Preço Final
0,Câmera Canon,999.99,Dólar,5.235800,5235.747642,1.40,7330.046699
1,Carro Renault,4500.00,Euro,5.522586,24851.635691,2.00,49703.271381
2,Notebook Dell,899.99,Dólar,5.235800,4712.167642,1.70,8010.684991
3,IPhone,799.00,Dólar,5.235800,4183.404200,1.70,7111.787140
4,Carro Fiat,3000.00,Euro,5.522586,16567.757127,1.90,31478.738541
5,Celular Xiaomi,480.48,Dólar,5.235800,2515.697184,2.00,5031.394368
6,Joia 20g,20.00,Ouro,307.210000,6144.200000,1.15,7065.830000

### Agora vamos exportar a nova base de preços atualizada

In [31]:
tabela.to_excel("Produtos_Novo.xlsx", index=False)